/*++

Module Name:

    device.c - Device handling events for example driver.

Abstract:

   This file contains the device entry points and callbacks.
    
Environment:

    Kernel-mode Driver Framework

--*/

#include "driver.h"
#include "device.tmh"

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, KC705pcidriverCreateDevice)
#endif

BOOLEAN KC705pcidriverInterruptISR(_In_ WDFINTERRUPT Interrupt, _In_ ULONG MessageID)
{
    UNREFERENCED_PARAMETER(MessageID);
    return WdfInterruptQueueDpcForIsr(Interrupt);
}
VOID KC705pcidriverInterruptDPC(_In_ WDFINTERRUPT Interrupt, _In_ WDFOBJECT AssociatedObject)
{
    UNREFERENCED_PARAMETER(AssociatedObject);
    PDEVICE_CONTEXT deviceContext = DeviceGetContext(WdfInterruptGetDevice(Interrupt));
    WDFREQUEST request = WdfDmaTransactionGetRequest(deviceContext->DmaTransaction);
    NTSTATUS status = STATUS_SUCCESS;
    WdfDmaTransactionDmaCompleted(deviceContext->DmaTransaction, &status);
    size_t bytesTransferred = WdfDmaTransactionGetBytesTransferred(deviceContext->DmaTransaction);
    WdfDmaTransactionRelease(deviceContext->DmaTransaction);
    WdfRequestCompleteWithInformation(request, STATUS_SUCCESS, bytesTransferred);
}

NTSTATUS
KC705pcidriverCreateDevice(
    _Inout_ PWDFDEVICE_INIT DeviceInit
    )
/*++

Routine Description:

    Worker routine called to create a device and its software resources.

Arguments:

    DeviceInit - Pointer to an opaque init structure. Memory for this
                    structure will be freed by the framework when the WdfDeviceCreate
                    succeeds. So don't access the structure after that point.

Return Value:

    NTSTATUS

--*/
{
    WDF_OBJECT_ATTRIBUTES deviceAttributes;
    PDEVICE_CONTEXT deviceContext;
    WDFDEVICE device;
    NTSTATUS status;

    PAGED_CODE();

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);

    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);

    if (!NT_SUCCESS(status))
    {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfDeviceCreate failed: %!STATUS!\n",
            status);
        return status;
	}
	//
	// Get a pointer to the device context structure that we just associated
	// with the device object. We define this structure in the device.h
	// header file. DeviceGetContext is an inline function generated by
	// using the WDF_DECLARE_CONTEXT_TYPE_WITH_NAME macro in device.h.
	// This function will do the type checking and return the device context.
	// If you pass a wrong object handle it will return NULL and assert if
	// run under framework verifier mode.
	//
	deviceContext = DeviceGetContext(device);

	//
	// Initialize the context.
	//
	deviceContext->PrivateDeviceData = 0;

	//
	// Create a device interface so that applications can find and talk
	// to us.
	//
	status = WdfDeviceCreateDeviceInterface(
		device,
		&GUID_DEVINTERFACE_KC705pcidriver,
		NULL // ReferenceString
	);

	if (!NT_SUCCESS(status))
    {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfDeviceCreateDeviceInterface failed: %!STATUS!\n",
            status);
        return status;
	}
    //
    // Initialize the I/O Package and any Queues
    //
    status = KC705pcidriverQueueInitialize(device);

    if (!NT_SUCCESS(status))
    {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "KC705pcidriverQueueInitialize failed: %!STATUS!\n",
            status);
        return status;
    }

    //
    // Get the BUS_INTERFACE_STANDARD for our device so that we can
    // read & write to PCI config space.
    //
    status = WdfFdoQueryForInterface(device,
        &GUID_BUS_INTERFACE_STANDARD,
        (PINTERFACE)&deviceContext->BusInterface,
        sizeof(BUS_INTERFACE_STANDARD),
        1, // Version
        NULL); //InterfaceSpecificData
    if (!NT_SUCCESS(status))
    {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfFdoQueryForInterface failed: %!STATUS!\n",
            status);
        return status;
    }

    DECLSPEC_ALIGN(MEMORY_ALLOCATION_ALIGNMENT) UCHAR buffer[sizeof(PCI_COMMON_CONFIG)];
    PPCI_COMMON_CONFIG  pPciConfig = (PPCI_COMMON_CONFIG)buffer;
    RtlZeroMemory(buffer, sizeof(buffer));
    ULONG bytesRead = deviceContext->BusInterface.GetBusData(
        deviceContext->BusInterface.Context,
        PCI_WHICHSPACE_CONFIG, //READ
        buffer,
        FIELD_OFFSET(PCI_COMMON_CONFIG, VendorID),
        sizeof(buffer));

    if (bytesRead != sizeof(buffer)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "GetBusData (sizeof(PCI_COMMON_CONFIG)) failed =%d\n",
            bytesRead);
        return STATUS_INVALID_DEVICE_REQUEST;
    }
    UNREFERENCED_PARAMETER(pPciConfig);

    // dont really care about that
    WdfDeviceSetAlignmentRequirement(device, FILE_OCTA_ALIGNMENT);

    // create DMA enabler
    WDF_DMA_ENABLER_CONFIG dma_enabler_config;
    WDF_DMA_ENABLER_CONFIG_INIT(&dma_enabler_config, WdfDmaProfilePacket64, 0x10000);
    status = WdfDmaEnablerCreate(device, &dma_enabler_config, NULL, &deviceContext->DmaEnabler);
    if (status != STATUS_SUCCESS)
    {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE, "WdfDmaEnablerCreate failed");
        return status;
    }

    // Lets just use a single transation object
    status = WdfDmaTransactionCreate(deviceContext->DmaEnabler, WDF_NO_OBJECT_ATTRIBUTES, &deviceContext->DmaTransaction);
    if (status != STATUS_SUCCESS)
    {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE, "WdfDmaTransactionCreate failed");
        return status;
    }

    // Create an interrupt for MSI
    WDF_INTERRUPT_CONFIG interrupt_config;
    WDF_INTERRUPT_CONFIG_INIT(&interrupt_config, &KC705pcidriverInterruptISR, &KC705pcidriverInterruptDPC);
    status = WdfInterruptCreate(device, &interrupt_config, WDF_NO_OBJECT_ATTRIBUTES, &deviceContext->Interrupt);
    if (status != STATUS_SUCCESS)
    {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE, "WdfInterruptCreate failed");
        return status;
    }
    return status;
}
